### ISSUE TITLE
Population Issues

### ISSUE THREAD

**Issue by ThePraeceps** [mishajw/vaxtldr.uk#2]
Hey,

I noticed you changed your data to be based off of English vaccination data but uses the population of the UK for it's percentages.

[According to the ONS](https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/populationestimates/bulletins/annualmidyearpopulationestimates/mid2019estimates#local-population-change) that makes the population total 56,286,961 oppose to 66m

You could solve this by doing a per-captia estimation for other nations, as vaccine supply is based off of this and is the current limiting factor.

Additonally I feel it is important to note that the vaccine hasn't been approved for children yet too, which may also adjust your predictions.

Thanks for making this website - it's a good place for some positivity rn, and I hope I can help make it more accurate.

**Comment by mishajw** [comment]
Fixed the population numbers. I'll open a separate issue for taking into account that only adults are planned to be vaccinated.

Thanks for the feedback!

**Comment by ThePraeceps** [comment]
I think you broke >80s unless there are 53.4 million of them ;)

**Comment by ThePraeceps** [comment]
I also believe that your "Predicting vaccinations" assumes an immediate doubling of vaccine supply to cover 2nd doses, although this might not be far from the truth if [Scotland's supply estimations](https://web.archive.org/web/20210113184220/https://www.gov.scot/binaries/content/documents/govscot/publications/strategy-plan/2020/12/coronavirus-covid-19-vaccine-deployment-plan-2021/documents/coronavirus-covid-19-vaccine-deployment-plan-2021/coronavirus-covid-19-vaccine-deployment-plan-2021/govscot%3Adocument/COVID-19%2BVaccine%2BDeployment%2BPlan%2B13%2BJanuary%2B2021.pdf) have held (once again, relevant due to per capita vaccine distribution), but once again is potentially noteworthy in the estimations.
