### ISSUE TITLE
Percent of over 80s uses under-80s total

### ISSUE THREAD

**Issue by tpritc** [mishajw/vaxtldr.uk#4]
The England total population is 56.3m, and it says over-80s are 53.4m. I new there were a lot of older folks in my little town in rural England but I didn't realize it was _that_ many! 😉

Presumably the under-80s totals and the over-80s totals are just mixed up here.

<img width="918" alt="image" src="https://user-images.githubusercontent.com/1939143/107376105-6800c980-6ae1-11eb-8e40-827b26780a09.png">

**Comment by tpritc** [comment]
Looks like this issue is that the formulas for under-80s and over-80s [are mixed up here](https://github.com/mishajw/vaxtldr.uk/blob/master/data/population.py#L9). I'll see if I can create a PR to fix it!

**Comment by mishajw** [comment]
As mentioned in the PR, spotted and [fixed](https://github.com/mishajw/vaxtldr.uk/commit/58f69493204d72a5fbc0a313379b884eee81dd0d) already, apologies!
