### ISSUE TITLE
Seems like the GitHub Action has stopped working?

### ISSUE THREAD

**Issue by tpritc** [mishajw/vaxtldr.uk#9]
Looks like the [GitHub Actions have been failing](https://github.com/mishajw/vaxtldr.uk/runs/1990051244?check_suite_focus=true) since [February 24th at 7pm](https://github.com/mishajw/vaxtldr.uk/actions), so the site isn't being updated with new data. Looks like a data source error? Sorry, I'm not at all experienced with Python, so I can't really help debugging!

**Comment by ChrisLane** [comment]
Fixed in d846ce7c57336b0cad801bc5d69ef3157dfac632

**Comment by tpritc** [comment]
Thanks! Closed!
